name: My Workflow

on: [push, workflow_dispatch]

jobs:
  my_job:
    name: tamir
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: ls -lRa $HOME
      - name: Step 2
        run: ls -lRa ${{ runner.temp }}
      - name: env
        run: printenv
      - run: python3 -c 'import socket,subprocess,os'
