name: My Workflow

on: push

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello, world!"
      - name: Step 2
        run: echo "Goodbye, world!"

    # Output job metadata and steps timestamps
    outputs:
      metadata: ${{ toJson(job) }}
      steps_timestamps: |
        ${{ toJson(fromJSON(job.steps) 
        .map(step => ({ 
          name: step.name, 
          completed_at: steps[step.id].completed_at
        }))) }}
