name: test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: printenv
        id: david
        name: TAMirKiviti
      - run: cat ${{ env.GITHUB_STEP_SUMMARY }}
        name: test
