name: tracee-profiler-github-action

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  Tracee-Scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start Tracee profiling in background
      uses: aquasecurity/tracee-action@e6a4241096569a753586623252a3ed02ae0e55ea

    - name: Your CI Pipeline Step
      run: for i in {1..10}; do sleep 1 && curl -sL -o /dev/null google.com; done

    - name: Stop and Check Tracee results and create a PR
      uses: aquasecurity/tracee-action@v0.1.0-stop
      with:
        fail-on-diff: "true"
        create-pr: "true"


